name: Deploy to CapRover

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.sha }} .
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.sha }}
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install CapRover CLI
        run: npm install -g caprover
      - name: Deploy App to CapRover
        run: |
          caprover deploy \
            --appToken ${{ secrets.CAPROVER_APP_TOKEN }} \
            --appName site \
            --caproverUrl https://${{ secrets.CAPROVER_SERVER }} \
            --imageName ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.sha }}
